/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

const char *brotli_compress_base64(const char *s) CF_SWIFT_NAME(brotli_compress_base64(s:));

const char *brotli_decompress_base64(const char *s) CF_SWIFT_NAME(brotli_decompress_base64(s:));

void brotli_free_string(char *s) CF_SWIFT_NAME(brotli_free_string(s:));
